[build]
# The index HTML file to drive the bundling process.
target = "crates/brush-app/index.html"
# The output dir for all final assets.
dist = "trunk_dist"
# The public URL from which assets are to be served.
public_url = "/brush-demo"
# Whether to include hash values in the output file names.
filehash = false
# Control minification: can be one of: never, on_release, always
minify = "on_release"
# Allow disabling sub-resource integrity (SRI)
no_sri = true
