[package]
name = "colmap-reader"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "io-util"] }

[lints]
workspace = true
