[target.aarch64-apple-ios]
linker = "ld"
ar = "ar"
rustflags = [
    "-C", "link-arg=-arch",
    "-C", "link-arg=arm64",
    "-C", "link-arg=-platform_version",
    "-C", "link-arg=ios",
    "-C", "link-arg=14.0",
    "-C", "link-arg=14.0",
    "-C", "link-arg=-syslibroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk",
    "-C", "link-arg=-lobjc",
    "-C", "link-arg=-lSystem",
    "-C", "link-arg=-framework",
    "-C", "link-arg=Foundation",
    "-C", "link-arg=-framework",
    "-C", "link-arg=UIKit"
]

[target.aarch64-apple-ios.env]
IPHONEOS_DEPLOYMENT_TARGET = "14.0"
SDKROOT = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
MACOSX_DEPLOYMENT_TARGET = ""

[build]
target = "aarch64-apple-ios"

[target.'cfg(target_os = "macos")']
rustflags = []