[package]
name = "brush-serde-macros"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
