on: [push, pull_request]

name: Rust

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  fmt-crank-check-test:
    name: Format + check + test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.82.0

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev # libgtk-3-dev is used by rfd
          version: 1.0
          execute_install_scripts: true

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: check --all-features
        run: cargo check --locked --all-features --all-targets

      - name: check default features
        run: cargo check --locked --all-targets

      - name: check --no-default-features
        run: cargo check --locked --no-default-features --lib --all-targets

      - name: cargo doc --lib
        run: cargo doc --lib --no-deps --all-features

      - name: cargo doc --document-private-items
        run: cargo doc --document-private-items --no-deps --all-features

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # ---------------------------------------------------------------------------

  check_wasm:
    name: Check wasm32 + wasm-bindgen
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.82.0
          targets: wasm32-unknown-unknown

      - run: sudo apt-get update && sudo apt-get install libgtk-3-dev libatk1.0-dev

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Check wasm32
        run: cargo check --lib --target wasm32-unknown-unknown

  # ---------------------------------------------------------------------------

  cargo-deny:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: aarch64-linux-android
          - target: i686-pc-windows-gnu
          - target: i686-pc-windows-msvc
          - target: i686-unknown-linux-gnu
          - target: wasm32-unknown-unknown
          - target: x86_64-apple-darwin
          - target: x86_64-pc-windows-gnu
          - target: x86_64-pc-windows-msvc
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-unknown-redox

    name: cargo-deny ${{ matrix.target }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "1.82.0"
          log-level: error
          command: check
          arguments: --target  ${{ matrix.target }}

  # ---------------------------------------------------------------------------

  android:
    name: android
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.82.0
          targets: aarch64-linux-android

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - run: cargo check -p brush-android --target aarch64-linux-android
        working-directory: crates/brush-android

  # ---------------------------------------------------------------------------

  tests:
    name: Run tests
    # We run the tests on macOS because it will run with a actual GPU
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all

      - name: Run doc-tests
        run: cargo test --doc
