name: Rust CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libatk1.0-dev libgtk-3-dev
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown, aarch64-linux-android
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build and run checks
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo build --all-features --verbose
          cargo build --target wasm32-unknown-unknown --all-features --verbose
          cargo test --all-features --verbose
