[target.aarch64-apple-ios]
linker = "xcrun"
ar = "xcrun ar"
rustflags = [
    "-C", "link-arg=-target",
    "-C", "link-arg=arm64-apple-ios",
    "-C", "link-arg=-isysroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk",
    "-C", "link-arg=-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib",
    "-C", "link-arg=-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks",
    "-C", "link-arg=-syslibroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
]

[build]
target = "aarch64-apple-ios"